### ISSUE TITLE
Remove extraneous attribution

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-frame#37]
Currently:

```
Leaflet | Tangram | © OSM contributors | Mapzen, Geocoding by Mapzen
```

We can remove `Geocoding by Mapzen`, which is added by the geocoder component inside of mapzen-ui. (Although this is slightly easier said than done.)

**Comment by nvkelso** [comment]
I'm seeing this credit in more and more blog posts which include Tangram Frame maps.

Since this issue was filed we also changed [Mapzen rights](https://mapzen.com/rights/) recommendation to:

`© <a href="https://www.mapzen.com/rights">Mapzen</a>,  <a href="https://openstreetmap.org/copyright">OpenStreetMap</a>
, and <a href="https://www.mapzen.com/rights/#services-and-data-sources">others</a>.`

I think `Leaflet | ` is always added by Leaflet, so if we want to credit Tangram (which seams reasonable since it's a promo for Tangram the product) than we'd do:

`<a href="https://mapzen.com/tangram">Tangram</a> | © <a href="https://www.mapzen.com/rights">Mapzen</a>, <a href="https://openstreetmap.org/copyright">OpenStreetMap</a>, and <a href="https://www.mapzen.com/rights/#services-and-data-sources">others</a>.`

This is configured on:

- https://github.com/tangrams/tangram-frame/blob/0d30585f712f8ffd6d34922db07f273ddff6cd89/main.js#L282

(And not specifically call out Geocoding, as that's covered in the general Mapzen credit, but would require other related changes at Lou notes above.)

**Comment by louh** [comment]
We recently swapped out the code under the hood of tangram-frame to use mapzen.js, which fixed the original extraneous attribution problem. Although mapzen.js automatically adds the recommended Mapzen rights, we were overwriting it here in tangram-frame. It may make sense to do the following instead:

- Allow mapzen.js to add the recommended Mapzen rights by default. If in the future our recommendation changes, upgrading mapzen.js will bring those in.
- use the map's attribution control method `addAttribution()` to append the credit to Tangram.

This would result in an attribution that looks like this (imagine the links):

`© Mapzen, OpenStreetMap, and others | Leaflet, Tangram`

**Comment by nvkelso** [comment]
Works for me :)
