### ISSUE TITLE
generate short URLs for scenes made in Tangram Play

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram-frame#40]
https://mapzen.com/tangram/view/&scene=https://mapzen.com/api/scenes/22/148/resources/default.yaml#15/37.7615/-122.4173

might become

https://mapzen.com/tangram/view/&api=22/148#15/37.7615/-122.4173

**Comment by burritojustice** [comment]
per @meetar, we don't need the query parameter at all!

https://mapzen.com/tangram/view/22/148#15/37.7615/-122.4173

**Comment by louh** [comment]
Wait, what? One does not simply create URL paths without further context!

**Comment by louh** [comment]
Let me add some more info!

When a URL has forward slashes in the path, a server will handle all of the routing until it reaches the "page" it needs to deliver to the client.

tangram-frame is a static client-side-only page. A URL like `https://mapzen.com/tangram/view/&api=22/148#15/37.7615/-122.4173` works because we can host this page at the `/view/` location. The server then serves the frame app, and it uses everything in the query string or hash to build a view.

But suppose we have url like this: `https://mapzen.com/tangram/view/22/148#15/37.7615/-122.4173` (no query parameter). This means the server will need to attempt to serve a page at `/view/22/148`. For a static page like tangram-frame, this is... unfeasible. One would need to deploy every possible directory and subdirectory with its own copy of tangram-frame to make this work.

But people obviously do this all the time. The solution, then, is to not use a static page. The server still parses these paths, but rather than serve a static page, it dynamically builds what it needs and sends it to the client. So, yes, query strings are not necessarily required for a view URL. But what this then implies is that we have an entirely different code base running on the server to build the correct view. It's a different environment, with different requirements, and it's not the same code.

Since no one has told me we're deprecating this repository in favor of a new server-side application I will assume that this is not what is happening at the moment, and so, yes, the query parameters are absolutely _still required_.

**Comment by meetar** [comment]
Agreed, and I'll thank @burritojustice to keep my half-baked, incoherent ramblings to himself in future.

**Comment by burritojustice** [comment]
hey I wanted `&api=`!

**Comment by meetar** [comment]
Reviewing this – was that a :+1: from @louh regarding an `api` parameter?

**Comment by louh** [comment]
To be perfectly honest, my gut tells me not to create an arbitrary number of custom parameters.

For this specifically, it assumes that a shorthand always maps to a known longhand. I don't know if we can guarantee this. We should talk about it though.

**Comment by louh** [comment]
OK: in considering the solution to this (https://github.com/tangrams/tangram-play/issues/682), and a related request in which the map scarab has access to a scene's "about page" - it seems the "short URL" is necessary to address all of these at once.

This is because Tangram View only has knowledge of a raw scene file. It does not actually know anything about the Tangram scene API and therefore has no information about a scene's metadata. In other words, by telling View to access the scene API instead of the raw scene file itself, we get access to:

1. The title
2. The description
3. The entry scene file (for my earlier comment I was only thinking of expanding short hand to a long form scene file URL, bypassing the API, and that was why I was hesitant to do that.)

I apologize if this connection was obvious to everyone _except_ me. In this context we can adequately justify the addition of another parameter. I hereby supply my 👍  for the `api` parameter.

**Comment by meetar** [comment]
`api` param added with https://github.com/tangrams/tangram-frame/pull/48 – testing requested 🙇

**Comment by louh** [comment]
Seems to work just fine! Thanks!
